### ISSUE TITLE
centos/rhel repository always overwritten

### ISSUE THREAD

**Issue by rndmh3ro** [nginxinc/ansible-role-nginx#1]
The following task runs twice, the first time with the variable `centos`, the second time with the variable `rhel`.
```
- name: "(Install: CentOS/RedHat) Add Mainline NGINX Repository"
  yum_repository:
    name: nginx
    baseurl: https://nginx.org/packages/mainline/{{ item }}/{{ ansible_distribution_major_version|int }}/$basearch/
    description: NGINX Repository
    enabled: yes
    gpgcheck: yes
  with_items:
    - centos
    - rhel
when: branch == "mainline"
```

However since the name of the repo is always `nginx`, the repo is always overwritten:
```
       TASK [nginxinc.nginx : (Install: CentOS/RedHat) Add Mainline NGINX Repository] ***
       --- before: /etc/yum.repos.d/nginx.repo
       +++ after: /etc/yum.repos.d/nginx.repo
       @@ -1,5 +1,5 @@
        [nginx]
       -baseurl = https://nginx.org/packages/mainline/rhel/6/$basearch/
       +baseurl = https://nginx.org/packages/mainline/centos/6/$basearch/
        enabled = 1
        gpgcheck = 1
        name = NGINX Repository
       
       changed: [localhost] => (item=centos) => {"changed": true, "item": "centos", "repo": "nginx", "state": "present"}
       --- before: /etc/yum.repos.d/nginx.repo
       +++ after: /etc/yum.repos.d/nginx.repo
       @@ -1,5 +1,5 @@
        [nginx]
       -baseurl = https://nginx.org/packages/mainline/centos/6/$basearch/
       +baseurl = https://nginx.org/packages/mainline/rhel/6/$basearch/
        enabled = 1
        gpgcheck = 1
        name = NGINX Repository
```

I briefly checked both repositories and at least for the rpms they seem to have the same content.
Possible solutions:
- always use the same url regardless of rhel or centos
- split the task into two task and check for the operating system.
