### ISSUE TITLE
Create more than one virtual server

### ISSUE THREAD

**Issue by adrianovieira** [nginxinc/ansible-role-nginx#101]
Thanks by your job doing this ansible role.

Please, how do I setup more than one virtual server?

As a sample example:
```shell
# /etc/nginx/conf.d/www1.example.com.conf
server {
    server_name www1.example.com;
    root /www/data/www1.example.com;
}

# /etc/nginx/conf.d/www2.example.com.conf
server {
    server_name www2.example.com;
    root /www/data/www2.example.com;
}
```

What I tried was (one of them acctualy):
```yaml
nginx_http_template:
  www1:
    conf_file_name: www1.example.com.conf
    server_name: www1.example.com
    #...
  www2:
    conf_file_name: www2.example.com.conf
    server_name: www2.example.com
    #...
```
But this doesn't work.

**Comment by gdzien** [comment]
Hello, 

My name is Grzegorz and I will work with you on solving issue you are facing.
At a first glance it seems that what you are doing should yield expected result, unfortunately I am unable to say what has gone wrong in your case without error message you are getting.

Can you please share messages returned by ansible when trying to use this role?

Sincerely,
Grzegorz Dzień

**Comment by adrianovieira** [comment]
Hi!

Thank you by helping me.

an inventory sample:
```yaml
      www2:
        template_file: http/default.conf.j2
        conf_file_name: www2.example.com.conf
        conf_file_location: /etc/nginx/conf.d/
        server_name: www2.example.com
        port: 80
        root: /usr/share/nginx/html/www2
```

1. creates unrequested `default.conf`  
```bash
$ ls -l /etc/nginx/conf.d/
total 12
-rw-r--r--. 1 root root 1093 Dez  4 13:01 default.conf
-rw-r--r--. 1 root root   80 Fev 13 13:46 www1.example.com.conf
-rw-r--r--. 1 root root   80 Fev 13 13:49 www2.example.com.conf
```

2. it doesn't insert a `root` path
```bash
$ cat /etc/nginx/conf.d/www2.example.com.conf 
# Ansible managed
server {
    listen 80;
    server_name www2.example.com;
}
```
