### ISSUE TITLE
Support for try_files

### ISSUE THREAD

**Issue by trusche** [nginxinc/ansible-role-nginx#116]
Hi!

I'm trying to configure the following nginx directive:

```
location / {
    try_files $uri/index.html $uri @app;
  }
```

But it seems `try_files` is not supported? I tried this:

```
      locations:
        default:
          location: /
          try_files: '$uri/index.html $uri @app'
```

which resulted in an error about undefined variable `html_file_location`. Then I tried 

```
      locations:
        default:
          location: /
          try_files: '$uri/index.html $uri @app'
          html_file_location: /usr/share/nginx/html
          html_file_name: index.html
          autoindex: false
```

which simply ignored the `try_files` line in the resulting directive.

Any plans to support this? Or am I missing something else?
