### ISSUE TITLE
Cannot find mime.types on FreeBSD (cleanup config task removes all files in specified path)

### ISSUE THREAD

**Issue by vladp** [nginxinc/ansible-role-nginx#136]
Hello,
I cannot seem to find mime.types (referred by main nginx.conf.j2) 
when using this role to install on FreeBSD 12.

my role code is:

```
---
# I have to set nginxconfigdir__root to /usr/local/etc/nginx on FreeBSD (on lnx it is /etc/nginx)
# (also will need to modify default template, because it hardcodes the pass to linux default, and does nto work on freebsd
# 
- name: install nginx | restapi
  include_role:
    name: nginxinc.nginx
    apply: 
      become: yes
  vars:
    nginx_type: opensource
    # this role has a problem installing modules for fbsd or obsd.
    # disable for now
#    nginx_modules:
#      image_filter: true
#      geoip: true
        
    # Remove previously existing NGINX configuration files.
    nginx_cleanup_config: true
    nginx_cleanup_config_path:
      - "{{ nginxconfigdir__root }}/config.d"  

    nginx_main_template_enable: true
    nginx_main_template:
      template_file: nginx.conf.j2 
      conf_file_name: nginx.conf
      conf_file_location: "{{ nginxconfigdir__root }}"  # I have to set it to /usr/local/etc/nginx on FreeBSD (on lnx it is /etc/nginx)
      user: nginx
      worker_processes: auto
      error_level: warn
      worker_connections: 1024
      http_enable: true
      http_settings:
        keepalive_timeout: 65
        cache: false
        rate_limit: false
        keyval: false
      stream_enable: true
      http_global_autoindex: false


    nginx_stream_template_enable: true
    nginx_stream_template:
      default:  
        template_file:  stream/default.conf.j2
        conf_file_name: restapi__beX.conf
        conf_file_location: "{{ nginxconfigdir__root }}/conf.d/stream"
        network_streams:
          default:
            listen_address: localhost
            listen_port: 4998
            udp_enable: false
            proxy_pass: mybackend
            proxy_timeout: 3s
            proxy_connect_timeout: 1s
            proxy_protocol: false
            health_check_plus: false
            proxy_ssl: 
              cert: "{{ currdomainCertDir }}/{{ certfile__fullchain }}"
              key: "{{ currdomainCertDir }}/{{ certfile__privkey }}"
              password_file: "{{ currdomainCertDir }}/{{ certfile__pass }}"
              protocols: TLSv1 TLSv1.1 TLSv1.2 TLSv1.3
              ciphers: HIGH:!aNULL:!MD5
              verify: false
              verify_depth: 1
              session_reuse: true  
              
        upstreams:
          upstream1: 
            name: mybackend
            zone_name: mybackend
            lb_method: least_conn
            sticky_cookie: false
            zone_size: 64k
            servers:
              server1:
                address: 10.0.1.99
                port: 77777
                weight: 1
                healthcheck: max_fails=2 fail_timeout=10s
              server2:
                address: 10.0.1.999
                port: 88888
                weight: 1
                healthcheck: max_fails=2 fail_timeout=10s

```
