### ISSUE TITLE
If catch-all ("_") is used as server_name and https_redirect is on nginx redirects to "_"

### ISSUE THREAD

**Issue by shokinn** [nginxinc/ansible-role-nginx#137]
If you want to have a catch-all server for http to redirect it to https it's currently not possible to do that because the following config is generated:  
```
#
# Ansible managed
#



server {
    listen 80;
    server_name _;
    return 301 https://_$request_uri;


}
```

The generated config should look like the following:  
```
#
# Ansible managed
#



server {
    listen 80;
    server_name _;
    return 301 https://$host$request_uri;


}
```

These are my ansible variables:  
```
nginx_http_template_enable: true
nginx_http_template:
  default:
    template_file: http/default.conf.j2
    conf_file_name: 99-https-rewrite.conf
    conf_file_location: /etc/nginx/conf.d/
    port: 80
    server_name: "_"
    https_redirect: true
```
