### ISSUE TITLE
Missing settings/vars that are rather critical

### ISSUE THREAD

**Issue by xTrekStorex** [nginxinc/ansible-role-nginx#155]
I know this role is still in development but just to provide a quick overview of settings/vars that are still missing and rather critical at least for most of our deployments:
- client_max_body_size
- ~proxy_buffering~
- proxy_redirect
- proxy_send_timeout
- send_timeout

not critical but nice to have:

- ~ssl_prefer_server_ciphers~

**Comment by xTrekStorex** [comment]
Just noticed there already are PRs for 

- proxy_buffering
- ssl_prefer_server_ciphers

**Comment by alessfg** [comment]
Thanks for the feedback @xTrekStorex!

**Comment by sangdrax8** [comment]
Unless I missed it in another ticket, I am also missing

- proxy_buffers
- proxy_buffer_size
- gzip (appears commented out in the default config)
- proxy_read_timeout


Would it not make sense to perhaps have a "additional options" dictionary that could accept any key/value pair and add them to the config?  At least it would allow usage of this module in places that require one of these before a pull request could have it added to the template officially?

**Comment by xTrekStorex** [comment]
> Unless I missed it in another ticket, I am also missing
> 
> * proxy_buffers
> * proxy_buffer_size
> * gzip (appears commented out in the default config)
> * proxy_read_timeout
> 
> Would it not make sense to perhaps have a "additional options" dictionary that could accept any key/value pair and add them to the config? At least it would allow usage of this module in places that require one of these before a pull request could have it added to the template officially?

proxy_read_timeout exists already 
https://github.com/nginxinc/ansible-role-nginx/blob/155c13c14058b3f86ca943882554af6c2240d1ab/defaults/main.yml#L282

the rest is indeed missing

**Comment by alessfg** [comment]
> Would it not make sense to perhaps have a "additional options" dictionary that could accept any key/value pair and add them to the config? At least it would allow usage of this module in places that require one of these before a pull request could have it added to the template officially?

I agree that implementing some sort of "additional options" dictionary would help, although I am not entirely sure what the best way to implement it would be. 

Right now I am thinking the best way would probably be to have to be a dictionary at each context level (think `http`, `stream`, `location`, etc...) for the dictionary to cover all use cases.

**Comment by atruskie** [comment]
An array of dicts (array of key-value pairs) might be more useful; it would allow for repeated lines.

An example from the docs:
```
    ssl_certificate     example.com.rsa.crt;
    ssl_certificate_key example.com.rsa.key;

    ssl_certificate     example.com.ecdsa.crt;
    ssl_certificate_key example.com.ecdsa.key;
```

Would be:

```yaml
nginx_http_template:
  default:
    ssl:
      additional:
        - ssl_certificate: example.com.rsa.crt
        - ssl_certificate_key: example.com.rsa.key
        - ssl_certificate: example.com.ecdsa.crt
        - ssl_certificate_key: example.com.ecdsa.key
```

**Comment by alessfg** [comment]
That's what I had in mind @atruskie 😄 -- hoping to have time to work on this sometime soon.

**Comment by bew** [comment]
Hello, I'm missing the worker related settings in `nginx.conf`, especially `worker_rlimit_nofile`.
I'll open a PR with this one if you don't mind

**Comment by alessfg** [comment]
I'm going to close this for now. There's a lot of NGINX directives that can be potentially critical in any given environment, and perhaps one day they'll all be natively supported by the templates in the role. However, for now, there's other priorities, and with the introduction of `custom_options`, you can now pass any of these directives to any given context without there being a need to explicitly support each directive.

**Comment by alexsegura** [comment]
+1 for gzip. Here is a copy-paste ready snippet for the lazy web ([source](https://www.digitalocean.com/community/tools/nginx))

```yaml
nginx_main_template_enable: true
nginx_main_template:
  # Other options
  http_custom_options:
    - gzip on
    - gzip_vary on
    - gzip_proxied any
    - gzip_comp_level 6
    - gzip_types text/plain text/css text/xml application/json application/javascript application/rss+xml application/atom+xml image/svg+xml
```
