### ISSUE TITLE
Creating custom conf file is confusing...

### ISSUE THREAD

**Issue by shanep2300** [nginxinc/ansible-role-nginx#178]
I'm confused on how to create a main template configuration.

Running into this error:

``fatal: [default]: FAILED! => {"changed": false, "cmd": ["nginx", "-T"], "delta": "0:00:00.011440", "end": "2019-11-06 20:13:01.886018", "msg": "non-zero return code", "rc": 1, "start": "2019-11-06 20:13:01.874578", "stderr": "nginx: [emerg] duplicate location \"/\" in /etc/nginx/conf.d/default_dynamic.conf:22\nnginx: configuration file /etc/nginx/nginx.conf test failed", "stderr_lines": ["nginx: [emerg] duplicate location \"/\" in /etc/nginx/conf.d/default_dynamic.conf:22", "nginx: configuration file /etc/nginx/nginx.conf test failed"], "stdout": "", "stdout_lines": []}``

All I want to do is make the conf file look like the following:

```
# For more information on configuration, see:
#   * Official English Documentation: http://nginx.org/en/docs/
#   * Official Russian Documentation: http://nginx.org/ru/docs/

user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /var/run/nginx.pid;

# Load dynamic modules. See /usr/share/doc/nginx/README.dynamic.
include /usr/share/nginx/modules/*.conf;

events {
    worker_connections 1024;
}

http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 2048;

    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;

    # Load modular configuration files from the /etc/nginx/conf.d directory.
    # See http://nginx.org/en/docs/ngx_core_module.html#include
    # for more information.
    include /etc/nginx/conf.d/*.conf;

    index   index.html index.htm;

    server {
        listen       9000 default_server;
        listen       [::]:9000 default_server;
        server_name  localhost;
        root         /usr/share/nginx/html;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;

        location / {
           root /home/ec2-user/sitespeed.io/sitespeed-result/folder;
           autoindex on;
        }

        # redirect server error pages to the static page /40x.html
        error_page 404 /404.html;
            location = /40x.html {
        }

        # redirect server error pages to the static page /50x.html
        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }        
    }     
}
```

**Comment by alessfg** [comment]
Hi @shanep2300! Looks like the location templating is failing at some stage -- can you share the playbook you are trying to deploy? I do not think it's possible to 100% recreate that sample config at the moment, but you can achieve the same end result using a couple configuration files. (Or alternatively, you can use the `nginx_main_upload_*` variables to push that exact configuration file to your target host).

**Comment by shanep2300** [comment]
Only messed with 3 files to try and achieve the conf file mentioned before. Everything else was left the same including tasks/*. A little new with ansible and templating, so sorry if I'm I bit slow on somethings. Let me know if you need anything else.

defaults/main.yml
```
---
# Install NGINX.
# Default is true.
nginx_enable: true

# Start NGINX service.
# Default is true.
nginx_start: true

# Print NGINX configuration file to terminal after executing playbook.
nginx_debug_output: true

# Specify which type of NGINX you want to install.
# Options are 'opensource' or 'plus'.
# Default is 'opensource'.
nginx_type: opensource
# Specify which version of NGINX you want to install.
# Default is empty.
# nginx_version: =19-1~bionic

# Specify repository origin for NGINX Open Source.
# Options are 'nginx_repository' or 'os_repository'.
# Only works if 'nginx_type' is set to 'opensource'.
# Default is nginx_repository.
nginx_install_from: nginx_repository

# Choose where to fetch the NGINX signing key from.
# Default is the official NGINX signing key host.
# nginx_signing_key: http://nginx.org/keys/nginx_signing.key

# Specify source repository for NGINX Open Source.
# Only works if 'install_from' is set to 'nginx_repository'.
# Defaults are the official NGINX repositories.
nginx_repository:
  alpine: >-
      https://nginx.org/packages/{{ (nginx_branch == 'mainline')
      | ternary('mainline/', '') }}alpine/v{{ ansible_distribution_version | regex_search('^[0-9]+\\.[0-9]+') }}/main
  debian:
    - >-
      deb https://nginx.org/packages/{{ (nginx_branch == 'mainline')
      | ternary('mainline/', '') }}{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} nginx
    - >-
      deb-src https://nginx.org/packages/{{ (nginx_branch == 'mainline')
      | ternary('mainline/', '') }}{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} nginx
  redhat: >-
      https://nginx.org/packages/{{ (nginx_branch == 'mainline')
      | ternary('mainline/', '') }}{{ (ansible_distribution == "RedHat")
      | ternary('rhel', 'centos') }}/{{ ansible_distribution_major_version }}/$basearch/
  suse: >-
      https://nginx.org/packages/{{ (nginx_branch == 'mainline')
      | ternary('mainline/', '') }}sles/{{ ansible_distribution_major_version }}

# Specify which branch of NGINX Open Source you want to install.
# Options are 'mainline' or 'stable'.
# Only works if 'install_from' is set to 'nginx_repository'.
# Default is mainline.
nginx_branch: stable

# Location of your NGINX Plus license in your local machine.
# Default is the files folder within the NGINX Ansible role.
nginx_license:
  certificate: license/nginx-repo.crt
  key: license/nginx-repo.key

# Delete NGINX Plus license after installation for security purposes.
# Default is true.
nginx_delete_license: false

# Install NGINX JavaScript, Perl, ModSecurity WAF (NGINX Plus only), GeoIP, Image-Filter, RTMP Media Streaming, and/or XSLT modules.
# Default is false.
nginx_modules:
  njs: false
  perl: false
  waf: false
  geoip: false
  image_filter: false
  rtmp: false
  xslt: false

# Install NGINX Amplify.
# Use your NGINX Amplify API key.
# Requires access to either the NGINX stub status or the NGINX Plus REST API.
# Default is null.
nginx_amplify_enable: false
nginx_amplify_api_key: null

# Install NGINX Controller.
# Use your NGINX Controller API key and NGINX Controller API endpoint.
# Requires NGINX Plus and write access to the NGINX Plus REST API.
# Default is null.
nginx_controller_enable: false
nginx_controller_api_key: null
nginx_controller_api_endpoint: null

# Install NGINX Unit and NGINX Unit modules.
# Use a list of supported NGINX Unit modules.
# Default is false.
nginx_unit_enable: false
nginx_unit_modules: null

# Remove previously existing NGINX configuration files.
# Use a list of paths you wish to remove.
# Default is false.
nginx_cleanup_config: false
nginx_cleanup_config_path:
  - /etc/nginx/conf.d

# Enable uploading NGINX configuration files to your system.
# Default for uploading files is false.
# Default location of files is the files folder within the NGINX Ansible role.
# Upload the main NGINX configuration file.
nginx_main_upload_enable: false
nginx_main_upload_src: conf/nginx.conf
nginx_main_upload_dest: /etc/nginx/
# Upload HTTP NGINX configuration files.
nginx_http_upload_enable: false
nginx_http_upload_src: conf/http/*.conf
nginx_http_upload_dest: /etc/nginx/conf.d/
# Upload Stream NGINX configuration files.
nginx_stream_upload_enable: false
nginx_stream_upload_src: conf/stream/*.conf
nginx_stream_upload_dest: /etc/nginx/conf.d/
# Upload HTML files.
nginx_html_upload_enable: false
nginx_html_upload_src: www/*
nginx_html_upload_dest: /usr/share/nginx/html
# Upload SSL certificates and keys.
nginx_ssl_upload_enable: false
nginx_ssl_crt_upload_src: ssl/*.crt
nginx_ssl_crt_upload_dest: /etc/ssl/certs/
nginx_ssl_key_upload_src: ssl/*.key
nginx_ssl_key_upload_dest: /etc/ssl/private/

# Enable creating dynamic templated NGINX HTML demo websites.
nginx_html_demo_template_enable: false
nginx_html_demo_template:
  default:
    template_file: www/index.html.j2
    html_file_name: index.html
    html_file_location: /usr/share/nginx/html
    web_server_name: Default

# Enable creating dynamic templated NGINX configuration files.
# Defaults are the values found in a fresh NGINX installation.
nginx_main_template_enable: true
nginx_main_template:
  template_file: nginx.conf.j2
  conf_file_name: nginx_dynamic.conf
  conf_file_location: /etc/nginx/
  user: nginx
  worker_processes: auto
  error_log:
    location: /var/log/nginx/error.log
    level: warn
  worker_connections: 1024
  http_enable: true
  http_settings:
    access_log_format:
      - name: main
        format: |-
          '$remote_addr - $remote_user [$time_local] "$request" '
          '$status $body_bytes_sent "$http_referer" '
          '"$http_user_agent" "$http_x_forwarded_for"'
    access_log_location:
      - name: main
        location: /var/log/nginx/access.log
    keepalive_timeout: 65
    cache: false
    rate_limit: false
    keyval: false
  http_global_autoindex: false
  stream_enable: false

# Enable creating dynamic templated NGINX HTTP configuration files.
# Defaults will not produce a valid configuration. Instead they are meant to showcase
# the options available for templating. Each key represents a new configuration file.
nginx_http_template_enable: true
nginx_http_template:
  default:
    template_file: http/default.conf.j2
    conf_file_name: default_dynamic.conf
    conf_file_location: /etc/nginx/conf.d/
    listen:
      listen_localhost:
        ip: localhost # Wrap in square brackets for IPv6 addresses
        port: 9000
        opts: [] # Listen opts like http2 which will be added (ssl is automatically added if you specify 'ssl:').
    server_name: localhost
    include_files: []
    error_page: /usr/share/nginx/html
    access_log:
      - name: main
        location: /var/log/nginx/access.log
    error_log:
      location: /var/log/nginx/error.log
      level: warn
    root: /usr/share/nginx/html
    https_redirect: false
    autoindex: true
    auth_basic: null
    auth_basic_user_file: null
    try_files: $uri $uri/index.html $uri.html =404
    client_max_body_size: 1m
    proxy_hide_headers: [] # A list of headers which shouldn't be passed to the application
    web_server:
      locations:
        default:
          location: /
          include_files: []
          proxy_hide_headers: [] # A list of headers which shouldn't be passed to the application
          html_file_location: /home/ec2-user/sitespeed-app/sitespeed-result/results
          html_file_name: index.html
          autoindex: true
          auth_basic: null
          auth_basic_user_file: null
          try_files: $uri $uri/index.html $uri.html =404
          client_max_body_size: 1m
      http_demo_conf: false
    returns:
      return301:
        location: /
        code: 301
        value: http://$host$request_uri

# Enable NGINX status data.
# Will enable 'stub_status' in NGINX Open Source and 'status' in NGINX Plus.
# Default is false.
nginx_status_enable: false
nginx_status_port: 8080

# Enable NGINX Plus REST API, write access to the REST API, and NGINX Plus dashboard.
# Requires NGINX Plus.
# Default is false.
nginx_rest_api_enable: false
nginx_rest_api_src: http/api.conf.j2
nginx_rest_api_location: /etc/nginx/conf.d/api.conf
nginx_rest_api_port: 8080
nginx_rest_api_write: false
nginx_rest_api_dashboard: false

# Enable creating dynamic templated NGINX stream configuration files.
# Defaults will not produce a valid configuration. Instead they are meant to showcase
# the options available for templating. Each key represents a new configuration file.
nginx_stream_template_enable: false
nginx_stream_template:
  default:
    template_file: stream/default.conf.j2
    conf_file_name: default.conf
    conf_file_location: /etc/nginx/conf.d/stream/
    network_streams:
      default:
        listen_address: localhost
        listen_port: 80
        udp_enable: false
        include_files: []
        proxy_pass: backend
        proxy_timeout: 3s
        proxy_connect_timeout: 1s
        proxy_protocol: false
        proxy_ssl:
          cert: /etc/ssl/certs/proxy_default.crt
          key: /etc/ssl/private/proxy_default.key
          trusted_cert: /etc/ssl/certs/proxy_ca.crt
          protocols: TLSv1 TLSv1.1 TLSv1.2
          ciphers: HIGH:!aNULL:!MD5
          verify: false
          verify_depth: 1
          session_reuse: true
        health_check_plus: false
    upstreams:
      upstream1:
        name: backend
        lb_method: least_conn
        zone_name: backend
        zone_size: 64k
        sticky_cookie: false
        servers:
          server1:
            address: localhost
            port: 8080
            weight: 1
            health_check: max_fails=1 fail_timeout=10s
```

With that I edited the template files
http/default.conf.j2

```
{{ ansible_managed | comment }}

{% if item.value.auth_request_http is defined %}
auth_request {{ item.value.auth_request_http }};
{% endif %}
{% if item.value.auth_request_set_http is defined %}
auth_request_set {{ item.value.auth_request_set_http.name }} {{ item.value.auth_request_set_http.value }};
{% endif %}

{% if item.value.http_custom_options is defined and item.value.http_custom_options | length %}
{% for inline_option in item.value.http_custom_options %}
{{ inline_option }};
{% endfor %}
{% endif %}

server {
{% for listen in item.value.listen %}
    listen {% if item.value.listen[listen].ip is defined and item.value.listen[listen].ip | length %}{{ item.value.listen[listen].ip }}:{% endif %}{{ item.value.listen[listen].port }}{% if item.value.ssl is defined and item.value.ssl %} ssl{% endif %}{% if item.value.listen[listen].opts is defined and item.value.listen[listen].opts | length %} {{ item.value.listen[listen].opts | join(" ") }}{% endif %};
{% endfor %}
    server_name {{ item.value.server_name | default('localhost') }};
{% if item.value.include_files is defined and item.value.include_files | length %}
{% for file in item.value.include_files %}
    include "{{ file }}";
{% endfor %}
{% endif %}
{% if item.value.proxy_hide_headers is defined %}
{% for header in item.value.proxy_hide_headers %}
    proxy_hide_header {{ header }};
{% endfor %}
{% endif %}
{% if item.value.auth_basic is defined and item.value.auth_basic %}
    auth_basic "{{ item.value.auth_basic }}";
{% endif %}
{% if item.value.auth_basic_user_file is defined and item.value.auth_basic_user_file %}
    auth_basic_user_file {{ item.value.auth_basic_user_file }};
{% endif %}
{% if item.value.root is defined and item.value.root %}
    root {{ item.value.root }};
{% endif %}
{% if item.value.https_redirect is defined and item.value.https_redirect %}
    return 301 https://{% if item.value.server_name == "_" %}$host{% else %}{{ item.value.server_name }}{% endif %}$request_uri;
{% endif %}
{% if item.value.autoindex is defined and item.value.autoindex %}
    autoindex on;
{% endif %}
{% if item.value.try_files is defined %}
    try_files {{ item.value.try_files }};
{% endif %}
{% if item.value.auth_request is defined %}
    auth_request {{ item.value.auth_request }};
{% endif %}
{% if item.value.auth_request_set is defined %}
    auth_request_set {{ item.value.auth_request_set.name }} {{ item.value.auth_request_set.value }};
{% endif %}
{% if item.value.client_max_body_size is defined and item.value.client_max_body_size %}
    client_max_body_size {{ item.value.client_max_body_size }};
{% endif %}
{% if item.value.server_custom_options is defined and item.value.server_custom_options | length %}
{% for inline_option in item.value.server_custom_options %}
    {{ inline_option }};
{% endfor %}
{% endif %}

{% if item.value.web_server is defined %}
{% for location in item.value.web_server.locations %}
    location {{ item.value.web_server.locations[location].location }} {
{% if item.value.web_server.locations[location].html_file_location is defined %}
        root   {{ item.value.web_server.locations[location].html_file_location }};
{% endif %}
{% if item.value.web_server.locations[location].html_file_name is defined %}
        index  {{ item.value.web_server.locations[location].html_file_name }};
{% endif %}
{% if item.value.web_server.locations[location].autoindex | default(false) %}
        autoindex on;
{% endif %}
{% if item.value.web_server.locations[location].try_files is defined %}
        try_files {{ item.value.web_server.locations[location].try_files }};
{% endif %}
{% if item.value.web_server.locations[location].include_files is defined and item.value.web_server.locations[location].include_files | length %}
{% for file in item.value.web_server.locations[location].include_files %}
        include "{{ file }}";
{% endfor %}
{% endif %}
{% if item.value.web_server.locations[location].custom_options is defined and item.value.web_server.locations[location].custom_options | length %}
{% for inline_option in item.value.web_server.locations[location].custom_options %}
        {{ inline_option }};
{% endfor %}
{% endif %}
{% if item.value.web_server.locations[location].proxy_hide_headers is defined %}
{% for header in item.value.web_server.locations[location].proxy_hide_headers %}
        proxy_hide_header {{ header }};
{% endfor %}
{% endif %}
{% if item.value.web_server.locations[location].returns is defined %}
{% for code in item.value.web_server.locations[location].returns %}
{% if item.value.web_server.locations[location].returns[code] is defined %}
        return {{ item.value.web_server.locations[location].returns[code].code }} {{ item.value.web_server.locations[location].returns[code].url }};
{% else %}
        return {{ item.value.web_server.locations[location].returns[code].url }};
{% endif %}
{% endfor %}
{% endif %}
{% if item.value.web_server.locations[location].auth_basic is defined and item.value.web_server.locations[location].auth_basic %}
        auth_basic "{{ item.value.web_server.locations[location].auth_basic }}";
{% endif %}
{% if item.value.web_server.locations[location].auth_basic_user_file is defined and item.value.web_server.locations[location].auth_basic_user_file %}
        auth_basic_user_file {{ item.value.web_server.locations[location].auth_basic_user_file }};
{% endif %}
{% if item.value.web_server.locations[location].auth_request is defined %}
        auth_request {{ item.value.web_server.locations[location].auth_request }};
{% endif %}
{% if item.value.web_server.locations[location].auth_request_set is defined %}
        auth_request_set {{ item.value.web_server.locations[location].auth_request_set.name }} {{ item.value.web_server.locations[location].auth_request_set.value }};
{% endif %}

    }
{% endfor %}
{% if item.value.web_server.http_demo_conf %}
    sub_filter_once off;
    sub_filter 'server_hostname' '$hostname';
    sub_filter 'server_address' '$server_addr:$server_port';
    sub_filter 'server_url' '$request_uri';
    sub_filter 'remote_addr' '$remote_addr:$remote_port';
    sub_filter 'server_date' '$time_local';
    sub_filter 'client_browser' '$http_user_agent';
    sub_filter 'request_id' '$request_id';
    sub_filter 'nginx_version' '$nginx_version';
    sub_filter 'document_root' '$document_root';
    sub_filter 'proxied_for_ip' '$http_x_forwarded_for';
{% endif %}
{% endif %}
{% if item.value.returns is defined %}
{% for return in item.value.returns %}
    location {{ item.value.returns[return].location }} {
        return {{ item.value.returns[return].code }}{% if item.value.returns[return].value is defined %} {{ item.value.returns[return].value }}{% endif %};
    }
{% endfor %}
{% endif %}
{% if item.value.error_page is defined %}
    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   {{ item.value.error_page }};
    }
{% endif %}

{% if item.value.access_log is defined %}
{% for access_log in item.value.access_log %}
    access_log  {{ access_log.location }}  {{ access_log.name }};
{% endfor %}
{% endif %}
{% if item.value.error_log is defined %}
    error_log {{ item.value.error_log.location }} {{ item.value.error_log.level }};
{% endif %}

}
```

and stream/default.conf.j2

```
{{ ansible_managed | comment }}

{% if item.value.custom_options is defined and item.value.custom_options | length %}
{% for inline_option in item.value.custom_options %}
{{ inline_option }};
{% endfor %}
{% endif %}

{% if item.value.network_streams is defined %}
{% for stream in item.value.network_streams %}
server {
{% if item.value.network_streams[stream].listen_address is defined and item.value.network_streams[stream].listen_port is defined %}
{% if item.value.network_streams[stream].listen_address == 'localhost' %}
{% if item.value.network_streams[stream].udp_enable %}
    listen {{ item.value.network_streams[stream].listen_port }} udp;
{% else %}
    listen {{ item.value.network_streams[stream].listen_port }};
{% endif %}
{% else %}
{% if item.value.network_streams[stream].udp_enable %}
    listen {{ item.value.network_streams[stream].listen_address }}:{{ item.value.network_streams[stream].listen_port }} udp;
{% else %}
    listen {{ item.value.network_streams[stream].listen_address }}:{{ item.value.network_streams[stream].listen_port }};
{% endif %}
{% endif %}
{% elif item.value.network_streams[stream].listen_port is defined %}
{% if item.value.network_streams[stream].udp_enable %}
    listen {{ item.value.network_streams[stream].listen_port }} udp;
{% else %}
    listen {{ item.value.network_streams[stream].listen_port }};
{% endif %}
{% endif %}
{% if item.value.network_streams[stream].include_files is defined and item.value.network_streams[stream].include_files | length %}
{% for file in item.value.network_streams[stream].include_files %}
    include "{{ file }}";
{% endfor %}
{% endif %}
    proxy_pass {{ item.value.network_streams[stream].proxy_pass }};
    proxy_timeout {{ item.value.network_streams[stream].proxy_timeout }};
    proxy_connect_timeout {{ item.value.network_streams[stream].proxy_connect_timeout }};
{% if item.value.network_streams[stream].proxy_protocol %}
    proxy_protocol on;
{% else %}
    proxy_protocol off;
{% endif %}
{% if item.value.network_streams[stream].proxy_ssl is defined %}
    proxy_ssl on;
{% if item.value.network_streams[stream].proxy_ssl.cert is defined %}
    proxy_ssl_certificate {{ item.value.network_streams[stream].proxy_ssl.cert }};
{% endif %}
{% if item.value.network_streams[stream].proxy_ssl.key is defined %}
    proxy_ssl_certificate_key {{ item.value.network_streams[stream].proxy_ssl.key }};
{% endif %}
{% if item.value.network_streams[stream].proxy_ssl.server_name is defined %}
    proxy_ssl_server_name {{ item.value.network_streams[stream].proxy_ssl.server_name | ternary("on", "off") }};
{% endif %}
{% if item.value.network_streams[stream].proxy_ssl.name is defined %}
    proxy_ssl_name {{ item.value.network_streams[stream].proxy_ssl.name }};
{% endif %}
{% if item.value.network_streams[stream].proxy_ssl.protocols is defined %}
    proxy_ssl_protocols {{ item.value.network_streams[stream].proxy_ssl.protocols }};
{% endif %}
{% if item.value.network_streams[stream].proxy_ssl.ciphers is defined %}
    proxy_ssl_ciphers {{ item.value.network_streams[stream].proxy_ssl.ciphers }};
{% endif %}
{% if item.value.network_streams[stream].proxy_ssl.trusted_cert is defined %}
    proxy_ssl_trusted_certificate {{ item.value.network_streams[stream].proxy_ssl.trusted_cert }};
{% endif %}
{% if item.value.network_streams[stream].proxy_ssl.verify is defined %}
    proxy_ssl_verify {{ item.value.network_streams[stream].proxy_ssl.verify | ternary("on", "off") }};
{% endif %}
{% if item.value.network_streams[stream].proxy_ssl.verify_depth is defined %}
    proxy_ssl_verify_depth {{ item.value.network_streams[stream].proxy_ssl.verify_depth }};
{% endif %}
{% if item.value.network_streams[stream].proxy_ssl.session_reuse is defined %}
    proxy_ssl_session_reuse {{ item.value.network_streams[stream].proxy_ssl.session_reuse | ternary("on", "off") }};
{% endif %}
{% endif %}
{% if item.value.network_streams[stream].health_check_plus %}
    health_check;
{% endif %}
{% if item.value.network_streams[stream].custom_options is defined and item.value.network_streams[stream].custom_options | length %}
{% for inline_option in item.value.network_streams[stream].custom_options %}
    {{ inline_option }};
{% endfor %}
{% endif %}
}
{% endfor %}
{% endif %}
```
