### ISSUE TITLE
Invalid reverse proxy example

### ISSUE THREAD

**Issue by rgarrigue** [nginxinc/ansible-role-nginx#187]
Hi there

To get started I c/c'ed the reverse proxy example from the README, the code block just after 

> This is a sample playbook file for deploying the Ansible Galaxy NGINX role in a localhost and installing the open source version of NGINX as a reverse proxy.

Which didn't worked, here's the debug message

```
TASK [nginxinc.nginx : (Setup: All NGINX) Dynamically Generate NGINX HTTP Configuration Files] *************************************************************************
task path: /opt/swarm/roles/nginxinc.nginx/tasks/conf/template-config.yml:49
failed: [i-00000000] (item={'key': 'default', 'value': {'template_file': 'http/default.conf.j2', 'conf_file_name': 'default.conf', 'conf_file_location': '/etc/nginx/conf.d/', 'listen': {'listen_localhost': {'ip': '0.0.0.0', 'port': 80, 'opts': ['default_server']}}, 'server_name': '_', 'error_page': '/usr/share/nginx/html', 'autoindex': False, 'reverse_proxy': {'locations': {'accessd': {'location': '/api/accessd', 'proxy_pass': 'http://localhost:10001'}, 'auth': {'location': '/api/auth', 'proxy_pass': 'http://localhost:10001'}, 'sub': {'location': '/api/sub', 'proxy_pass': 'http://localhost:10002'}}}}}) => {
    "changed": false,
    "item": {
        "key": "default",
        "value": {
            "autoindex": false,
            "conf_file_location": "/etc/nginx/conf.d/",
            "conf_file_name": "default.conf",
            "error_page": "/usr/share/nginx/html",
            "listen": {
                "listen_localhost": {
                    "ip": "0.0.0.0",
                    "opts": [
                        "default_server"
                    ],
                    "port": 80
                }
            },
            "reverse_proxy": {
                "locations": {
                    "auth": {
                        "location": "/api/auth",
                        "proxy_pass": "http://localhost:10001"
                    },
                    "sub": {
                        "location": "/api/sub",
                        "proxy_pass": "http://localhost:10002"
                    }
                }
            },
            "server_name": "_",
            "template_file": "http/default.conf.j2"
        }
    },
    "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'port'"
}
```

Problem's in `default.conf.j2` L52

        listen {{ item.value.port }} ssl;

So I had to do like other examples do, add a port: 80

```yaml
nginx_http_template_enable: true
nginx_http_template:
  default:
    port: 80                                        # <================== here
    template_file: http/default.conf.j2
    conf_file_name: default.conf
    conf_file_location: /etc/nginx/conf.d/
    listen:
      listen_localhost:
        ip: 0.0.0.0
        port: 80
        opts:
          - default_server
    server_name: _
    ...
```

Not exactly clean since it's a duplicated information, but now it works.

Best regards,
