### ISSUE TITLE
setup-controller-repository doesn't check OS family

### ISSUE THREAD

**Issue by TuxInvader** [nginxinc/ansible-role-nginx#223]
Controller setup from repository (with provided API key) fails on Ubuntu because the yum_repository module barfs.

Fixed my local copy by adding a "when" clause.

```
- name: "(Install: Debian/Ubuntu) Add NGINX Controller Agent Repository"
  apt_repository:
    filename: nginx-controller
    repo: deb https://packages.nginx.org/controller/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release | lower }} controller
  when: ansible_os_family == "Debian"

- name: "(Install: CentOS/RedHat) Add NGINX Controller Agent Repository"
  yum_repository:
    name: nginx-controller
    baseurl: https://packages.nginx.org/controller/centos/$releasever/$basearch/
    description: NGINX Controller Agent
    gpgcheck: yes
  when: ansible_os_family == "RedHat"
```
