### ISSUE TITLE
custom_options such as maps should not end in semi-colon

### ISSUE THREAD

**Issue by rgarrigue** [nginxinc/ansible-role-nginx#226]
Hi there

I want to avoid logging Googlebot & co. Here's how I do it

```yaml
nginx_main_template_enable: true
nginx_main_template:
  user: nginx
  worker_processes: 1
  error_log:
    location: /var/log/nginx/error.log
    level: warn
  worker_connections: 1024
  http_enable: true
  http_settings:
    access_log_format:
      - name: main
        format: '''$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for"'''
    access_log_location:
      - location: /var/log/nginx/access.log
        name: main if=$log_ua
    keepalive_timeout: 65
    cache: false
    rate_limit: false
    keyval: false
  http_custom_options:
    # Map various probes User Agent that we don't want to see in the log
    - "map $http_user_agent $log_ua { ~Googlebot 0; ~worldping-api 0; ~Go-http-client.* 0; ~Consul\\ Health\\ Check 0; default 1; } #"
  stream_enable: false
```

But changing this conf doesn't restart the Nginx, only reload, which is not enough.

```
TASK [nginxinc.nginx : (Setup: All NGINX) Dynamically Generate NGINX Main Configuration File] ****************************************************************************************************************************************************************************************************************************************************************************************
--- before: /etc/nginx/nginx.conf
+++ after: /root/.ansible/tmp/ansible-local-18448gttn2rgf/tmp1ylkgqzb/nginx.conf.j2
@@ -31,7 +31,7 @@
 
     #gzip  on;
     resolver 127.0.0.1 valid=30s ipv6=off;
-    map $http_user_agent $log_ua { ~Googlebot 0; ~worldping-api 0; ~Go-http-client.* 0; ~Consul\ Health\ Check 0; default 1; };
+    map $http_user_agent $log_ua { ~Googlebot 0; ~worldping-api 0; ~Go-http-client.* 0; ~Consul\ Health\ Check 0; default 1; } #;
     include /etc/nginx/conf.d/*.conf;
 }
 

changed: [i-0e2e44bc5e8d52ee0]

...

RUNNING HANDLER [nginxinc.nginx : (Handler: All OSs) Reload NGINX] *******************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [i-0e2e44bc5e8d52ee0]
```

I'm not sure changing /etc/nginx/nginx.conf should be a restart every single time though.

Another thing, a corner case : a `map` shouldn't end up with `;`. I had to finish with `# ` to comment out the `;`.

Best regards,
