### ISSUE TITLE
Cannot create unix socket upstream

### ISSUE THREAD

**Issue by milliams** [nginxinc/ansible-role-nginx#232]
I am trying top use this role to reproduce the setup described in the [Gunicorn documentation
](https://gunicorn-docs.readthedocs.io/en/latest/deploy.html) which has an upstream section like:

```nginx
upstream app_server {
  server unix:/run/gunicorn.sock fail_timeout=0;
}
```

I set the `upstream` section of the config to be:

```yaml
        upstreams:
          app_server:
            name: app_server
            servers:
              gunicorn:
                address: unix:/run/gunicorn.sock
                health_check: fail_timeout=0
```

but when I run ansible, I get the following error:

```
msg: 'AnsibleUndefinedVariable: ''dict object'' has no attribute ''port'''
```

The problem here seems to be that the template `templates/http/default.conf.j2` is assuming the presence of the `port` key:

```jinja
{% for server in item.value.upstreams[upstream].servers %}
    server {{ item.value.upstreams[upstream].servers[server].address }}:{{ item.value.upstreams[upstream].servers[server].port }} weight={{ item.value.upstreams[upstream].servers[server].weight|default("1") }} {{ item.value.upstreams[upstream].servers[server].health_check|default("") }};
{% endfor %}
```

to create a `server 192.168.0.7:8000`-style entry but in my case, I want to create a Unix socket connection.

**My environment:**
Latest version of the role from Galaxy
Ansible 2.9.3
CentOS 7

**Comment by alessfg** [comment]
Good catch. I did not account for unix sockets when implementing upstreams so thanks for reporting the issue!

While I get a fix merged can you try using upstream custom options instead? You should be able to input any directive you wish into the upstream block this way.

**Comment by milliams** [comment]
I replaced:

```yaml
upstreams:
  app_server:
    name: app_server
    sticky_cookie: false
    servers:
      gunicorn:
        address: unix:/run/gunicorn.sock
        health_check: fail_timeout=0
```

with

```yaml
upstreams:
  app_server:
    name: app_server
    sticky_cookie: false
    custom_options:
      - server unix:/tmp/gunicorn.sock fail_timeout=0
    servers: []
```

and it correctly creates:

```nginx
upstream app_server {
    server unix:/tmp/gunicorn.sock fail_timeout=0;
}

That workaround is good enough for now, thanks.
```
