### ISSUE TITLE
Conditionals in locations / no automatic colon after custom_options lines

### ISSUE THREAD

**Issue by xTrekStorex** [nginxinc/ansible-role-nginx#234]
**Is your feature request related to a problem? Please describe.**
There currently is no way, that I am aware of, to define conditionals in locations.
custom_options always add a colon at the end of the line ( https://github.com/nginxinc/ansible-role-nginx/blob/master/templates/http/default.conf.j2#L400 ), which usually is great but due to this it can't be used to add a conditional like 
`if (!-f $document_root$fastcgi_script_name) { return 404; }`
since that creates an invalid config syntax.

**Describe the solution you'd like**
A way to define conditional blocks in locations like with the multiple servers approach.

**Describe alternatives you've considered**

- A flag to toggle the colon though at this point one might as well just add the colon to the string in YAML and remove it from the template.
- Add the line in question to fastcgi_params or, in a cleaner way, a dedicated include file.
But that seems messy.

**Additional context**
Related var:
```
[...]
 xtrekstorex_net:
    conf_file_name: xtrekstorex_net.conf
    servers:
      xtrekstorex_net_http:
        listen:
          listen_localhost:
            ip: 127.0.0.1
            port: 8080
        server_name: xtrekstorex.net
        access_log:
          - name: combined
            location: /var/log/nginx/xtrekstorex.net_access.log
        error_log:
          location:  /var/log/nginx/xtrekstorex.net_error.log
          level: warn
        web_server:
          http_demo_conf: false 
          locations:
            default:
              location: /
              html_file_location: "{{ gluster_mount_dir }}/www/xtrekstorex.net"
            php:
              location: ~ \.php$
              html_file_location: "{{ gluster_mount_dir }}/www/xtrekstorex.net"
              custom_options:
                - fastcgi_split_path_info ^(.+?\.php)(\/.*|)$
                - if (!-f $document_root$fastcgi_script_name) { return 404; }
                - "fastcgi_pass unix:/run/php/php{{ php_version }}-fpm.sock"
                - include fastcgi_params 
   
[...]         
```

Result:
```
server {
    listen 127.0.0.1:8080;
    server_name xtrekstorex.net;


    location / {
        root   /gluster/webroot/www/xtrekstorex.net;

    }
    location ~ \.php$ {
        root   /gluster/webroot/www/xtrekstorex.net;
        fastcgi_split_path_info ^(.+?\.php)(\/.*|)$;
        if (!-f $document_root$fastcgi_script_name) { return 404; };
        fastcgi_pass unix:/run/php/php7.4-fpm.sock;
        include fastcgi_params;

    }

    access_log  /var/log/nginx/xtrekstorex.net_access.log combined;
    error_log /var/log/nginx/xtrekstorex.net_error.log warn;

}
```
