### ISSUE TITLE
Allow to optionally tell systemd to restart nginx on failure 

### ISSUE THREAD

**Issue by rgarrigue** [nginxinc/ansible-role-nginx#244]
**Is your feature request related to a problem? Please describe.**

I've a (Consul) service discovery based infrastructure on EC2. Rebooting development environment (aka without the redundancy) often end up in Nginx failing to restart since it's unable to resolve backends service URLs (authentification.service.consul for example)

**Describe the solution you'd like**

I ended up adding a systemd drop-in to restart Nginx. There's no risk in there, systemd will mark the service as stuck if too much restart attempts happens

```yaml
  tasks:
    - name: Nginx systemd service drop-in to force restart
      copy:
        content: |
          # Managed by Ansible
          [Service]
          Restart=on-failure
          RestartSec=30s
        mode: 0444
        dest: /lib/systemd/system/nginx.d/restart-on-failure.conf
        notify:
          - reload systemd
          - restart nginx
      tags: always
```

Since I don't like adding tasks above a dedicated role, here is a feature request. Would make sense in this role I think.

**Describe alternatives you've considered**

There's no easy alternative, imho what I'm implementing here is a "retry" feature that is meant to be part of any services in a micro services architecture.

**Comment by magicalyak** [comment]
I could take a stab at this.  Do you think adding a variable for drop-in service file makes sense?  I already have code for this on the build-from-source option for OSS.

**Comment by alessfg** [comment]
Seconds is fine IMO (different use cases might warrant different sleep timers).

**Comment by rgarrigue** [comment]
Agreed, specifying the timer to enable it if fine imho.

**Comment by magicalyak** [comment]
@rgarrigue The combined [PR here](https://github.com/nginxinc/ansible-role-nginx/pull/272) should allow you to specify the time for systemd.  I've added the following to a systemd.yml defaults that hopefully make obvious the changes.  I also added a timeout.  You need to make nginx_service_modify: true for either of the two options to take effect.

```yaml
---
# Enable systemd modifications
# ** ALL of the following variables are ignored unless this is set to true **
nginx_service_modify: false

# Remove the override file completely
nginx_service_clean: false

# Override the systemd directory
# Default is /etc/systemd/system/nginx.service.d
nginx_service_overridepath: /etc/systemd/system/nginx.service.d

# Override the systemd filename
# Default is override.conf
nginx_service_overridefilename: override.conf

# Set service timeout for systemd systems in seconds (default: 90)
# [Service]
# TimeoutStopSec=90
# Default is to comment this out
# nginx_service_timeoutstopsec: 90

# Set the restart policy for systemd systems
# Values = no (default), on-failure, on-abnormal, on-watchdog, on-abort, always
# [Service]
# Restart=on-failure
# Default is to comment this out
# nginx_service_restart: on-failure

# Set the restart timer in seconds
# [Service]
# RestartSec=5s
# Default is to comment this out
# nginx_service_restartsec: 5s

# Enable a custom systemd override file
# ** This could break the service **
# Setting this to true disables custom values above
nginx_service_custom: false

# Filename and path for systemd override file
# Setting this will overwrite existing override file
nginx_service_custom_file: "{{ role_path }}/files/services/nginx.override.conf"
```
