### ISSUE TITLE
Example of ssl termination with nginx reverse proxy

### ISSUE THREAD

**Issue by VilleMiekkoja** [nginxinc/ansible-role-nginx#254]
**Is your feature request related to a problem? Please describe.**
Kind of. I wish to terminate ssl with nginx, and simultaneously apply it as reverse proxy. I do not see an example of this in the docs, even I think it is pretty common scenario.

**Describe the solution you'd like**
Just an example configuration on how to terminate ssl with reverse proxy

**Describe alternatives you've considered**
I've considered applying nginx reverse proxy with ssl termination without this role. Like just manually configuring nginx, if it is too hard with this.

**Comment by xTrekStorex** [comment]
You can take the examples and expand them with the dict objects taken from the templates defaults:  https://github.com/nginxinc/ansible-role-nginx/blob/master/defaults/main/template.yml

Something like this:
```
nginx_http_template_enable: true
nginx_http_template:
  jira_mydomain_net:
    conf_file_name: jira_mydomain_net.conf
    servers:
      first:
        listen:
          listen_public:
            ip: 0.0.0.0
            port: 443
            ssl: true
        server_name: jira.mydomain.net
        ssl:
          cert: /etc/ssl/certs/jira.mydomain.net.crt
          key: /etc/ssl/private/jira.mydomain.net.key
        access_log:
          - name: combined
            location: /var/log/nginx/jira.mydomain.net_access.log
        error_log:
          location: /var/log/nginx/jira.mydomain.net_error.log
          level: warn
        reverse_proxy:
          locations:
            default:
              location: /
              proxy_pass: http://jira01.local.mydomain.net:8080
```

I left out ssl ciphers, dhparam, proxy_set_header etc since I set them in the main config, but you can just take them from the examples or defaults. Same for using upstreams.
