### ISSUE TITLE
set  nginx_debug_output: true  then script Failed 

### ISSUE THREAD

**Issue by darkman13** [nginxinc/ansible-role-nginx#271]
**Describe the bug**
Setting the nginx_debug_output variable to true in the script results in the following error.

**To reproduce**

shell> ansible-playbook -i hosts provision.yml

1. Deploy NGINX role using playbook.yml
```
# provision.yml
- name: server provisioning
  hosts: servers
  pre_tasks:
  - name: "Set repo if RedHat"
    set_fact:
      version: "-1.17.10-1.el{{ ansible_distribution_major_version }}.ngx"
  roles:
    - role: nginxinc.nginx
      become: true
      become_user: root
  vars:
    nginx_debug_output: true
    nginx_version: "{{ version }}"
    nginx_logrotate_conf_enable: true
    nginx_logrotate_conf:
      paths:
        - "/var/log/nginx/*.log"
      options:
        - daily
        - missingok
        - rotate 14
        - compress
        - delaycompress
        - notifempty
        - sharedscripts
```
2. View output/logs/configuration on '...'
```
TASK [nginxinc.nginx : (Setup: All OSs) Register NGINX configuration] **************************************
fatal: [test-ansible.aws.hosts......]: FAILED! => {"changed": false, "cmd": "nginx -T", "msg": "[Errno 2] No such file or directory.", "rc": 2}
```
3. See error

**Expected behavior**

**Your environment:**
 - Version of the NGINX Role or specific commit
```
- nginxinc.nginx (0.14.0) was installed successfully
```
 - Version of Ansible
````
ansible 2.9.9
````
 - Target deployment platform
```
CentOS Linux release 7.8.2003 (Core)
```
**Additional context**

**Comment by alessfg** [comment]
Thanks for reporting this issue @darkman13! (And sorry for accidentally closing it -- I misclicked 😅) I have encountered this issue myself a couple times and I think I know why it happens in some distros (`nginx_debug_output` runs `nginx -T` before the `nginx` service is started).

**Comment by darkman13** [comment]
> (`nginx_debug_output` runs `nginx -T` before the `nginx` service is started).

I don't think this is a problem.
Some executions on centos seem to require root privileges (for running commands like "rpm logrotate and nginx" )
```
  roles:
    - role: nginxinc.nginx
      become: true
      become_user: root
```
but, execution in the handler does not seem to apply this root permission.
Would you please check it again?

**Comment by alessfg** [comment]
`nginx_debug_output` runs before any handler is run, so whether the handler runs correctly as root or not would be a different issue altogether (not saying that it's not an issue). I've also recently heard of some CentOS issues related to SELinux, which should be able to be addressed with the introduction of SELinux handling variables in a PR merged yesterday (#272).

**Comment by darkman13** [comment]
@alessfg Sorry. I was misunderstanding that part.

**Comment by darkman13** [comment]
Share additional errors and solutions.

When executing the script with the following options

```
---
- name: server provisioning
  hosts: servers
  become: true
  collections:
  - nginxinc.nginx_controller
  roles:
    - nginx
  vars:

    nginx_debug_output: false
    nginx_logrotate_conf_enable: true
```

An error occurs in the Run Logrotate section.

```

TASK [nginx : (Config: All OSs) Run Logrotate] ********************************************************************************************************************************************
fatal: [pierre-ansible.aws.server]: FAILED! => {"changed": true, "cmd": "logrotate -f /etc/logrotate.d/nginx", "msg": "[Errno 2] No such file or directory.", "rc": 2}

```

After looking for why this error occurred, it seems that some value of the PATH environment variable is missing when the script is executed (I can't figure out why this happens)

```
ok: [pierre-ansible.aws.server]] => {
    "result": {
        "changed": true,
        "cmd": [
            "env"
        ],
        ... skip ....
         "PATH=/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/openjdk-jdk/bin",
         # No /usr/sbin value
        ... skip ....

```


So, I confirmed that there is no problem if the environment variable is forcibly set when the script is executed.

```
- name: server provisioning
  hosts: servers
  become: true
  become_user: root
  tasks:
    - name: "execute env"
      command: env
      register: result 

    - debug:
        var: result
  
    - name: "Run Logrotate"
      command: logrotate -f /etc/logrotate.d/nginx
  environment:
    PATH: $PATH:/usr/sbin
```

Please refer.
Thanks
