### ISSUE TITLE
Broke backwards compatibility template PID

### ISSUE THREAD

**Issue by EJBroeders** [nginxinc/ansible-role-nginx#275]
Commit 902d4ff83f8b6485a7900a16302ffa690a455e97 broke backwards compatibility. My initial config was, based on  `molecule/common/playbook_template.yml`:
```
...
  - role: nginxinc.nginx
    tags: [ nginx ]
    vars:
      nginx_main_template_enable: true
      nginx_main_template:
        template_file: nginx.conf.j2
        conf_file_name: nginx.conf
        conf_file_location: /etc/nginx
        user: nginx
        worker_processes: auto
        error_log:
          location: /var/log/nginx/error.log
          level: warn
        worker_connections: 1024
        http_enable: true
        http_settings:
          access_log_format:
          - name: main
            format: |
              '$remote_addr - $remote_user [$time_local] "$request" '
              '$status $body_bytes_sent "$http_referer" '
              '"$http_user_agent" "$http_x_forwarded_for"'
          access_log_location:
          - name: main
            location: /var/log/nginx/access.log
          keepalive_timeout: 65
          cache: false
          rate_limit: false
          keyval: false
          server_tokens: "off"
        http_global_autoindex: false
        stream_enable: false
      nginx_http_template_enable: true
...
```
This results in:
```
TASK [nginxinc.nginx : (Setup: All NGINX) Dynamically Generate NGINX Main Configuration File] ****************************************
fatal: [dev1]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'pid'"}
```
The fix on my side is easy: add the `pid` variable. However, I would expect that new development should not break older configurations without a prior warning.

As a more general inquiry, would it be possible to add variable defaults within nested variables, such as this? Or would it be possible to add defaults within the Jinja2 templates?

I would prefer to have the defaults within the templates; it would make sense as a user and developer to have them there because before setting a variable I already inspect the templates on how they are used.
