### ISSUE TITLE
Syntax error on tasks/conf/template-config.yml

### ISSUE THREAD

**Issue by langnix** [nginxinc/ansible-role-nginx#30]
There is a syntax-error in template-config.yml in the conditions:
`when: default_exists.stat.exists && main_template_enable`

when running with:
```
---
- hosts: localhost
  become: true
  roles:
    - role: nginxinc.nginx
  vars:
    - main_template_enable: true
```
this bounces with
```
."msg": "The conditional check 'default_exists.stat.exists && main_template_enable' failed. The error was: template error while templating string: unexpected char u'&' at 33
```

To fix: replace the '&&' with 'and'
