### ISSUE TITLE
`nginx_http_template.[default].servers.[server1].listen.[listen_items]` is not insertion ordered

### ISSUE THREAD

**Issue by StudioMaX** [nginxinc/ansible-role-nginx#301]
**Describe the bug**
All listen records inside `nginx_http_template.[default].servers.[server1].listen.[listen_items]` won't preserve their insertion position/order inside ~~array~~ dict.

**To reproduce**
```yaml
nginx_http_template:
  default:
    servers:
      server1:
        listen:
          listen_ipv4_http:
            ip: "1.2.3.4"
            port: 80
            opts:
              - default_server
              - deferred
          listen_ipv4_https:
            ip: "1.2.3.4"
            port: 443
            ssl: true
            opts:
              - http2
              - default_server
              - deferred
          listen_ipv4_front:
            ip: "1.2.3.4"
            port: 5757
            opts:
              - default_server
          listen_ipv6_http1:
            ip: "[fe80::a00:abcd::aaaa]"
            port: 80
            opts:
              - default_server
              - deferred
          listen_ipv6_http2:
            ip: "[fe80::a00:abcd::bbbb]"
            port: 80
            opts:
              - default_server
              - deferred
          listen_ipv6_https1:
            ip: "[fe80::a00:abcd::aaaa]"
            port: 443
            ssl: true
            opts:
              - http2
              - default_server
              - deferred
          listen_ipv6_https2:
            ip: "[fe80::a00:abcd::bbbb]"
            port: 443
            ssl: true
            opts:
              - http2
              - default_server
              - deferred
          listen_ipv6_front:
            ip: "[fe80::a00:abcd::cccc]"
            port: 5757
            opts:
              - default_server
```

**Expected result**
```
listen 1.2.3.4:80 default_server deferred;
listen 1.2.3.4:443 ssl http2 default_server deferred;
listen 1.2.3.4:5757 default_server;
listen [fe80::a00:abcd::aaaa]:80 default_server deferred;
listen [fe80::a00:abcd::bbbb]:80 default_server deferred;
listen [fe80::a00:abcd::aaaa]:443 ssl http2 default_server deferred;
listen [fe80::a00:abcd::bbbb]:443 ssl http2 default_server deferred;
listen [fe80::a00:abcd::cccc]:5757 default_server;
```

**Actual result**
```
listen 1.2.3.4:80 default_server deferred;
listen [fe80::a00:abcd::cccc]:5757 default_server;
listen [fe80::a00:abcd::aaaa]:443 ssl http2 default_server deferred;
listen [fe80::a00:abcd::bbbb]:443 ssl http2 default_server deferred;
listen 1.2.3.4:443 ssl http2 default_server deferred;
listen [fe80::a00:abcd::bbbb]:80 default_server deferred;
listen [fe80::a00:abcd::aaaa]:80 default_server deferred;
listen 1.2.3.4:5757 default_server;
```

**Your environment:**
-   Version of the NGINX Role or specific commit: master# 0922304b12c2dc578f86537f311304ffc498057d
-   Version of Ansible: 2.9.11
-   Target deployment platform: CentOS 7

**Additional context**
As far as I know, this is because that the keys in `dict` [do not preserve their order](https://stackoverflow.com/questions/39501901/create-a-ansible-dictionary-which-keeps-order), and because of this they can be displayed with a random order.
Some additional info: https://github.com/ansible/ansible/issues/36886, https://github.com/ansible/ansible/pull/36644

This issue would not have happened if a `list` was used instead of a `dict`, for example:
```yaml
        listen:
          - ip: "1.2.3.4"
            port: 80
            opts:
              - default_server
              - deferred
          - ip: "1.2.3.4"
            port: 443
            ssl: true
            opts:
              - http2
              - default_server
              - deferred
```
instead of:
```yaml
        listen:
          listen_ipv4_http:
            ip: "1.2.3.4"
            port: 80
            opts:
              - default_server
              - deferred
          listen_ipv4_https:
            ip: "1.2.3.4"
            port: 443
            ssl: true
            opts:
              - http2
              - default_server
              - deferred
```

But this will be a BC.
Any ideas how we can keep listens in their insertion order? Because if there are several listen directives, the order of the lines in the finished default.conf looks weird, and you can get confused in it while trying to understood.
