### ISSUE TITLE
OSS version no longer installs on Amazon Linux

### ISSUE THREAD

**Issue by edjackson-wf** [nginxinc/ansible-role-nginx#329]
**Describe the bug**
NGINX open source no longer installs via this role on Amazon Linux 2.

**To reproduce**
1. Deploy NGINX role using playbook.yml on an Amazon Linux system
2. View ansible output
3. See error "Your OS, Amazon is not supported by NGINX Open Source"

**Expected behavior**
NGINX open source version installed.

**Your environment:**
-   Version of the NGINX role: 0.17.0
-   Ansible: 2.9.13
-   Target deployment platform: Amazon Linux 2

**Additional context**
This appears to be a result of #319, where Amazon was included in the list for commercial version but not for the OSS version. Prior to this change, this role worked fine on AL2.

**Comment by alessfg** [comment]
That's intended. If you want to use NGINX on Amazon Linux I recommend using the `nginx_install_from: source` option.

**Comment by edjackson-wf** [comment]
AFAIK Amazon Linux is binary compatible with RHEL, and installation via version 0.16.0 of this role works fine.

I would happily just install NGINX from the repos that AWS provides, but unfortunately they don't update regularly enough to satisfy my security audit requirements.

While installing from source is certainly an option, it seems like an unnecessary burden.

**Comment by alessfg** [comment]
You make a valid point. Let me think about it and get back to you. Either way, as a PSA, even if NGINX RHEL packages work on Amazon Linux, NGINX will not support any potential issues arisen from installing NGINX on Amazon Linux.

**Comment by edjackson-wf** [comment]
Thanks for considering it.

For what it's worth (mostly to people who hit this via google, I guess), the following tasks will probably suffice as a substitute in most cases, although configuration files will still need to be managed and the service enabled:

```yaml
- name: Add nginx repo
  # NOTE: This is explicitly configured for RHEL7, which should work for AL2
  yum_repository:
    name: nginx
    baseurl: "https://nginx.org/packages/rhel/7/$basearch"
    description: Official NGINX repository for RHEL
    enabled: yes
    gpgcheck: yes
    gpgkey: https://nginx.org/keys/nginx_signing.key
    mode: 0644

- name: Install NGINX
  yum:
    name: nginx
    state: latest
    disablerepo: "*"
    enablerepo: nginx
    update_cache: yes
```
