### ISSUE TITLE
Failure on Installing 

### ISSUE THREAD

**Issue by AchimGrolimund** [nginxinc/ansible-role-nginx#456]
https://github.com/nginxinc/ansible-role-nginx/blob/d25945b2c386b816dab03e5a24c47ac307013d30/tasks/opensource/install-redhat.yml#L2

```
Stdout: fatal: [localhost]: FAILED! => 
{
    "changed": false,
    "msg": "Unsupported parameters for (yum_repository) module: module_hotfixes Supported parameters include: async, attributes, backup, bandwidth, baseurl, content, cost, delimiter, deltarpm_metadata_percentage, deltarpm_percentage, description, directory_mode, enabled, enablegroups, exclude, failovermethod, file, follow, force, gpgcakey, gpgcheck, gpgkey, group, http_caching, include, includepkgs, ip_resolve, keepalive, keepcache, metadata_expire, metadata_expire_filter, metalink, mirrorlist, mirrorlist_expire, mode, name, owner, params, password, priority, protect, proxy, proxy_password, proxy_username, regexp, remote_src, repo_gpgcheck, reposdir, retries, s3_enabled, selevel, serole, setype, seuser, skip_if_unavailable, src, ssl_check_cert_permissions, sslcacert, sslclientcert, sslclientkey, sslverify, state, throttle, timeout, ui_repoid_vars, unsafe_writes, username"
}
```

Host: EC2 RedHat 8 Instance

i run the Role without anything.

```
# 00-requirements.yml
- src: nginxinc.nginx
  name: nginx
```

```
# 01-install-requirements.yml
- name: Install prerequisite roles
  hosts: localhost
  become_user: root
  become: true

  tasks:
    - name: Install required roles for base image playbook
      command: ansible-galaxy install -r 00-requirements.yml -p roles/
```

```
# main
- name: Install Roles
  hosts: localhost
  become_user: root
  become: true

  roles:
    - role: nginx
```

Did anyone know what happens with this error?

greetings
