### ISSUE TITLE
GPG Error installing amplify in Ubuntu Focal (20lts)

### ISSUE THREAD

**Issue by ChrisMcKee** [nginxinc/ansible-role-nginx#486]
* Ubuntu 20.04lts (focal)

During packer creation the amplify step fails 

```
    amazon-ebs.nginx-ami: TASK [nginxinc.nginx : Debug NGINX output] *************************************
    amazon-ebs.nginx-ami: skipping: [127.0.0.1]
    amazon-ebs.nginx-ami:
    amazon-ebs.nginx-ami: TASK [nginxinc.nginx : Configure logrotate for NGINX] **************************
    amazon-ebs.nginx-ami: skipping: [127.0.0.1]
    amazon-ebs.nginx-ami:
    amazon-ebs.nginx-ami: TASK [nginxinc.nginx : Install NGINX Amplify] **********************************
    amazon-ebs.nginx-ami: included: /tmp/packer-provisioner-ansible-local/620679bd-4084-fd12-1773-88a5b7506141/roles/nginxinc.nginx/tasks/amplify/install-amplify.yml for 127.0.0.1
    amazon-ebs.nginx-ami:
    amazon-ebs.nginx-ami: TASK [nginxinc.nginx : Configure NGINX Amplify agent repository] ***************
    amazon-ebs.nginx-ami: included: /tmp/packer-provisioner-ansible-local/620679bd-4084-fd12-1773-88a5b7506141/roles/nginxinc.nginx/tasks/amplify/setup-debian.yml for 127.0.0.1
    amazon-ebs.nginx-ami:
    amazon-ebs.nginx-ami: TASK [nginxinc.nginx : (Debian/Ubuntu) Add NGINX Amplify agent repository] *****
    amazon-ebs.nginx-ami: skipping: [127.0.0.1]
    amazon-ebs.nginx-ami:
    amazon-ebs.nginx-ami: TASK [nginxinc.nginx : (Ubuntu 20.04) Add NGINX Amplify agent repository] ******
    amazon-ebs.nginx-ami: fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: W:GPG error: https://packages.amplify.nginx.com/py3/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY ABF5BD827BD9BF62, E:The repository 'https://packages.amplify.nginx.com/py3/ubuntu focal InRelease' is not signed."}
```
