### ISSUE TITLE
Bug with lograte formating

### ISSUE THREAD

**Issue by tibz7** [nginxinc/ansible-role-nginx#672]
### Describe the bug

logrotate "daily" is badly formatted

### To reproduce

1. Just run the role normally I guess its a default behavour
2. `cat /etc/logrotate.d/nginx`
```
{
    d
    a
    i
    l
    y
    postrotate
        if [ -f /var/run/nginx.pid ]; then
            kill -USR1 `cat /var/run/nginx.pid`
        fi
    endscript
}

```

### Your environment

- 0.8.0
- Version of 2.15

- Target deployment platform
debian 12

**Comment by alessfg** [comment]
Hey @tibz7 -- I cannot reproduce this error.

When I use the following playbook:

```yaml
---
- name: Converge
  hosts: all
  tasks:
    - name: Install NGINX
      ansible.builtin.include_role:
        name: nginxinc.nginx
      vars:
        nginx_logrotate_conf_enable: true
        nginx_logrotate_conf:
          paths:
            - /var/log/nginx/*.log
          options:
            - daily
```

This is what I get:

```console
[root@almalinux-8 /]# cat /etc/logrotate.d/nginx
/var/log/nginx/*.log
{
    daily
    postrotate
        nginx -s reopen
    endscript
}
```
