### ISSUE TITLE
main_template_enable, http_template_enable, stream_template_enable

### ISSUE THREAD

**Issue by robgarner** [nginxinc/ansible-role-nginx#7]
Hi -

Re: main_template_enable, http_template_enable, stream_template_enable

Can you give us some idea what you have in mind for implementing these vars, and whether or not they're on your radar for a near or far timeframe ?

Thanks,
-Rob

**Comment by alessfg** [comment]
Hi @robgarner!

The variables are already implemented (although admittedly the implementation is very basic at this stage). The idea is to use `main_template_*` to manage the `nginx.conf` file, `http_template_*` to manage `http` blocks, and `stream_template_*` to manage `stream` blocks. 

For example, you can use `main_template_enable` by setting its value to `true`. You can then set other values such as `main_template_user` or `main_template_error_level` to tweak `nginx.conf` values (you can find these values and their defaults at `defaults/main.yml`).

As far as further development of NGINX templating goes - the plan is to gradually add support for all the major NGINX directives - starting with the main `nginx.conf` templating, then moving to `http` blocks, and finally moving to `stream` blocks.

**Comment by Uhanga88** [comment]
Hi there!
Guys, could you please provide any updates regarding the variables using in nginx.conf and templates of http blocks?  Will it be possible to use j2 templates for generating virtual hosts in the next releases?

Thanks in advance!

**Comment by alessfg** [comment]
@Uhanga88 support for virtual hosts is still on the roadmap but I cannot provide an ETA.  Re `nginx.conf` templating are there any extra specific variables that you'd like to see included in the [`nginx.conf.j2`](https://github.com/nginxinc/ansible-role-nginx/blob/master/templates/nginx.conf.j2) template?

**Comment by sseide** [comment]
For the time until all this variables are implemented it would be really helpful to have role variables specifying my own template to use instead of the one provided by the role iteself. Currently (as far as i understand) it is only possible to push my own configuration files via copy - there are no modifications possible anymore at this point and i have to somehow create them locally as needed as the copy operation in use does not allow setting remote source (an file i templated before) as copy source.

Or do i miss something?

Thanks in advance

**Comment by alessfg** [comment]
Quick update - more advanced main/http templating options are almost done and ready to be released. The way templates work has been slightly reworked and should hopefully provide further flexibility on how to approach templating.

**Comment by carlba** [comment]
I have implemented faux vhost support by doing this

```yaml
- name: install and configure the reverse proxied HTTPS servers
  include_role:
    name: nginxinc.nginx
  vars:
    nginx_http_template_enable: true
    nginx_http_template:
      '{{ vhost.name }}':
        port: 443
        server_name: "{{ vhost.fqdn }}"
        autoindex: false
        template_file: http/default.conf.j2
        conf_file_name: '{{ vhost.name }}.conf'
        conf_file_location: /etc/nginx/conf.d/
        ssl:
          cert: "/etc/letsencrypt/live/{{ vhost.fqdn }}/fullchain.pem"
          key: "/etc/letsencrypt/live/{{ vhost.fqdn }}/privkey.pem"
        web_server:
          locations: []
          http_demo_conf: false
        reverse_proxy:
          locations:
            backend:
              location: /
              proxy_pass: 'http://{{ vhost.name }}'
              websocket: true
          health_check_plus: false
        upstreams:
          '{{ vhost.name }}':
            name: '{{ vhost.name }}'
            lb_method: least_conn
            zone_name: '{{ vhost.name }}'
            zone_size: 64k
            sticky_cookie: false
            servers:
              '{{ vhost.name }}':
                address: '{{ vhost.local_ip }}'
                port: '{{ vhost.local_port }}'
                weight: 1
                health_check: max_fails=1 fail_timeout=10s
    nginx_html_demo_template_enable: false
  loop: '{{ proxied_vhosts }}'
  loop_control:
    loop_var: 'vhost'
```
