### ISSUE TITLE
GPG invalid signatures

### ISSUE THREAD

**Issue by leandroembu** [nginxinc/ansible-role-nginx#731]
### Describe the bug

There's some invalid GPG signatures on Debian 11 and 12

### To reproduce

1. Deploy the Ansible NGINX role using `playbook.yml`
2. Try to update target system with `apt update & apt upgrade`
3. See error:

`W: Failed to fetch https://nginx.org/packages/mainline/debian/dists/bookworm/InRelease  The following signatures were invalid: EXPKEYSIG ABF5BD827BD9BF62 nginx signing key <signing-key@nginx.com>`

### Expected behavior

A working update with no signature issues.

### Your environment

- Version of the Ansible NGINX role or specific commit: `nginxinc.nginx, 0.24.1`
- Version of Ansible: `ansible [core 2.14.3]`
- Target deployment platform: Debian 11 and 12

**Comment by inntran** [comment]
Have you tried switch to use the main branch? I faced same issue of RPM distros.
My requirements.yml:
```
roles: 
  - name: nginxinc.nginx
    version: 'a34243d8d8ba136d0d291c13b48ec95e3e9c8f3c' # up-to-date main branch as of 2024-07-10
    src: https://github.com/nginxinc/ansible-role-nginx
```
