### ISSUE TITLE
Nginx can't find directories ? 

### ISSUE THREAD

**Issue by ren21** [nginxinc/ansible-role-nginx#86]
Hi there!

I'm trying to run this ansible playbook, copied from the galaxy site:
```
---
- hosts: servertest
  become: true
  roles:
    - nginxinc.nginx // can I even do this ? using ansible-nginx-role doesn't work
  vars:
    nginx_http_template_enable: true
    nginx_http_template:
      default:
        port: 80
        server_name: <<host ip address>> // or it's not that kind of name ? 
        error_page: /usr/share/nginx/html
        autoindex: false
        web_server:
          locations:
            default:
              location: /
              html_file_location: /usr/share/nginx/html
              html_file_name: index.html
```
As you can probably tell, I hardly modified anything other than the server name and the host on which I'm running the playbook. I get this error message though:

`fatal: [ngintest@192.168.1.78]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'conf_file_location'\n\nThe error appears to have been in '/home/md21/.ansible/roles/nginxinc.nginx/tasks/conf/template-config.yml': line 24, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"(Setup: All NGINX) Ensure NGINX HTTP Directory Exists\"\n  ^ here\nThis one looks easy to fix.  It seems that there is a value started\nwith a quote, and the YAML parser is expecting to see the line ended\nwith the same kind of quote.  For instance:\n\n    when: \"ok\" in result.stdout\n\nCould be written as:\n\n   when: '\"ok\" in result.stdout'\n\nOr equivalently:\n\n   when: \"'ok' in result.stdout\"\n"}`

As far as I can tell there's a problem with the yml syntax, some line not ending with the correct quote type, or something like that.

Can I get some help, I don't fully understand the problem, I checked everywhere and can't seem to find it. 
~ Matt

**Comment by alessfg** [comment]
Hi there @ren21! Let me address your questions one by one.

```
roles:
    - nginxinc.nginx // can I even do this ? using ansible-nginx-role doesn't work
```

As you already figured out, if you download the role from Ansible Galaxy you need to use `nginxinc.nginx` as your role name instead of `ansible-role-nginx`. The README erroneously uses `ansible-role-nginx` in one of the examples.

```
server_name: <<host ip address>> // or it's not that kind of name ? 
```

`server_name` refers to the NGINX `server_name` directive. You can find details on how to use it here https://nginx.org/en/docs/http/server_names.html.

```
---
- hosts: servertest
  become: true
  roles:
    - nginxinc.nginx // can I even do this ? using ansible-nginx-role doesn't work
  vars:
    nginx_http_template_enable: true
    nginx_http_template:
      default:
        port: 80
        server_name: <<host ip address>> // or it's not that kind of name ? 
        error_page: /usr/share/nginx/html
        autoindex: false
        web_server:
          locations:
            default:
              location: /
              html_file_location: /usr/share/nginx/html
              html_file_name: index.html
```

Once again, the README examples are not entirely correct. You are missing some variables that need to be in place for the playbook to work. The following playbook should work

```
---
- hosts: servertest
  become: true
  roles:
    - nginxinc.nginx
  vars:
    nginx_http_template_enable: true
    nginx_http_template:
      default:
        template_file: http/default.conf.j2
        conf_file_name: default.conf
        conf_file_location: /etc/nginx/conf.d/
        port: 80
        server_name: localhost
        error_page: /usr/share/nginx/html
        autoindex: false
        web_server:
          locations:
            default:
              location: /
              html_file_location: /usr/share/nginx/html
              html_file_name: index.html
              autoindex: false
          http_demo_conf: false
```

As a rule of thumb it looking at `defaults/main.yml` or some of the playbooks in `tests/playbooks/` will give you a good idea of what you can or you can't do. However, it is also true that Ansible Galaxy only shows you the README and the examples in the README need to be drastically improved. I'll start work on that asap.
