### ISSUE TITLE
nginx_version is applied only on main package but not module

### ISSUE THREAD

**Issue by mixman68** [nginxinc/ansible-role-nginx#861]
> [!CAUTION]
> Remember to redact any sensitive information such as authentication credentials or license keys.

### Describe the bug

I set explicit version of nginx (1.27.3) and I get 1.27.4 when modules are installed. but 1.27.3 if not modules installed

### To reproduce

Steps to reproduce the bug:

Play this playbook
```
---
- name: Reverse proxy
  hosts:
    - reverseProxies
  vars:
    nginx_version: =1.27.3-1~bookworm
    nginx_modules:
       - geoip
       - image-filter
       - njs
       - perl
       - xslt
  tasks:
    - name: "NGINX role"
      ansible.builtin.include_role:
        name: nginxinc.nginx
```

### Expected behavior

Have Nginx 1.27.3

### Your environment

- Version of the Ansible NGINX role (or specific commit): 0.25.0
- Version of Ansible: 2.17.5
- How is Ansible being managed (CLI/pipeline/Automation Hub/etc...): ansible-playbook
- Target deployment platform(s): Debian 12
