### ISSUE TITLE
Configuring basic authorization (auth_basic)

### ISSUE THREAD

**Issue by platan** [nginxinc/ansible-role-nginx#98]
I would like to configure [basic authorization](https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/). It seems that currently I need my own [default.conf.j2](https://github.com/nginxinc/ansible-role-nginx/blob/master/templates/http/default.conf.j2) template. And this is what I'm using:
```jinja
{% for location in item.value.reverse_proxy.locations %}
    location {{ item.value.reverse_proxy.locations[location].location }} {
{# this part below is an extra configuration #}
{% if item.value.reverse_proxy.locations[location].auth_basic is defined %}
        auth_basic "{{ item.value.reverse_proxy.locations[location].auth_basic }}";
{% endif %}
{% if item.value.reverse_proxy.locations[location].auth_basic_file is defined %}
        auth_basic_user_file {{ item.value.reverse_proxy.locations[location].auth_basic_file }};
{% endif %}
{# this part above is an extra configuration #}
        proxy_pass {{ item.value.reverse_proxy.locations[location].proxy_pass }};
{% if item.value.reverse_proxy.health_check_plus is defined and item.value.reverse_proxy.health_check_plus %}
        health_check;
{% endif %}
```
plus:
```yml
          locations:
            prometheus:
              location: /prometheus/
              proxy_pass: http://localhost:9090
              auth_basic: "Restricted Content"
              auth_basic_file: /etc/nginx/.htpasswd.prometheus
```
I would like to be able to configure basic authorization by one of the following options:
1. Using dedicated configuration options like `auth_basic` and `auth_basic_file`
1. By generic configuration option like 
```yml
          locations:
            prometheus:
                extra_options: >
                  auth_basic: "Restricted Content"
                  auth_basic_user_file: /etc/nginx/.htpasswd.prometheus
```
What do you think about this feature and suggested solutions?
